env:
  browser: true
  commonjs: true
  es11: true
extends:
  - 'plugin:react/recommended'
  - '../.eslintrc.yml'
  - 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - varsIgnorePattern: "_.*"
